### ISSUE TITLE
Some differences between raw results and Table 4

### ISSUE THREAD

**Issue by jvamvas** [alexwarstadt/blimp#4]
Thanks for providing this great resource!

Looking at the table of raw results (https://github.com/alexwarstadt/blimp/blob/master/raw_results/blimp_full_results_summary.csv), I noticed that a few dozen cells differ from Table 4 in the paper.

For example, for the paradigm "inchoative", the paper reports:
```
5-gram	LSTM	TXL	GPT-2	Human
89 	72 	81 	90 	95 
```

The corresponding data in the CSV (please note the different column order):
```
LSTM	GPT2	TXL	N-Gram	human
0.653	0.683	0.543	0.509	0.82
```

Which version of the data should be cited?

**Comment by jvamvas** [comment]
@alexwarstadt FYI, I've just run the code myself, and based on the results for TXL it seems that the raw results are the ones that  should be cited.

**Comment by alexwarstadt** [comment]
Hi Jannis---Thanks for bringing these mistakes to our attention and for your work to replicate our results. You're correct that there were mistakes in Table 4 and in the GPT-2 results throughout. We've updated the github with a [revised results file](https://github.com/alexwarstadt/blimp/blob/master/raw_results/summary/models_summary.jsonl) and ask that you consult that file for official results. To help with replication, we've also released [model outputs](https://github.com/alexwarstadt/blimp/tree/master/raw_results/all_outputs) for all the sentences in BLiMP.
